#!/usr/bin/perl
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

use Pod::Usage;

if ( $#ARGV == -1 ) { 
	pod2usage(-verbose => 1);	
}

my $last = "";
my $comment = "";
open(my $fh, "<", $ARGV[0]);
while (<$fh>) {
	if ( /^([^ :]+):(.*)/ ) { 
		if ( $last ne $1 && $last ne "" ) { 
			print "}\n\n";
		}

		my @p = split(/ +/, $2);
		print $comment;
		print "void $1 (void) {\n";
		
		$last = $1;
		$comment = "";

	} elsif ( /^(.*):=(.*)$/ ) { 
		print "$1 = $2;";
	} elsif ( s/^###/\/\/\/ \\file $ARGV[0]\n\/\/\/ \\brief / ) { 
		print;
	} elsif ( /^##/ ) { 
		s/^##/\/\/\//;
		$comment = $_;
	} else { 
		print;
	}
}
print "}\n";
close($fh);


=head1 NAME

./doxyfilter-Makefile.pl file

=head1 SYNOPSIS

Modifies bash input to bo compatible with doxygen.

Replaces ## to //.

=cut


