#!/usr/bin/perl
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

use Pod::Usage;

if ( $#ARGV == -1 ) { 
	pod2usage(-verbose => 1);	
}

my $keepLine=1;
my $cleanEmptyLine=0;
open(my $fh, "<", $ARGV[0]);
while (<$fh>) {
 	if ( /function / ) {
		s/function ([^ {\n]+)/function $1 ()/;
		print;		
	} else {
		if ( /##/ ) { 
			$keepLine = 2;
		}
		if ( /^[}{]/ ) { 
			$keepLine = 1;
		}
		
		if ( /^###/ ) {
			s/^###/\/\/\/ \\file $ARGV[0]\n\/\/\/ \\brief /;
			$cleanEmptyLine++;
		}
		
		s/^##US(.*)/##$1\\n/;
		s/^##/\/\/\//;		
		
		if ( $keepLine > 0 ) { 
			print;
		} else { 
			if ( $cleanEmptyLine == 0 ) {
				print "\n";
			} else { 
				$cleanEmptyLine--;
			}
		}
		$keepLine--;
	}
}
close($fh);


=head1 NAME

./doxyfilter-bash.pl file

=head1 SYNOPSIS

Modifies bash input to bo compatible with doxygen.

Replaces ## to //.

=cut


