#!/usr/bin/perl
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

use Pod::Usage;

if ( $#ARGV == -1 ) { 
	pod2usage(-verbose => 1);	
}

open(my $fh, "<", $ARGV[0]);
while (<$fh>) {
 	if ( /^\s*if / || /^\s*fi/ ) { 
		next;
	} elsif ( /function / ) {
		s/function ([^ {\n]+)/function $1 ()/;
		print;		
	} else {
		s/^###/\/\/\/ \\file $ARGV[0]\n\/\/\/ \\brief /;
		s/^##/\/\/\//;
		print;
	}
}
close($fh);


=head1 NAME

./doxyfilter-bash.pl file

=head1 SYNOPSIS

Modifies bash input to bo compatible with doxygen.

Replaces ## to //.

=cut


